apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canteen.fullname" . }}
  labels:
    {{- include "canteen.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "canteen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "canteen.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: {{ include "canteen.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef: { name: {{ include "canteen.fullname" . }}-env }
            - secretRef:    { name: {{ include "canteen.fullname" . }}-secrets }
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds:       {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds:       {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- if .Values.dataProtection.enabled }}
          volumeMounts:
            - name: dp-keys
              mountPath: /root/.aspnet/DataProtection-Keys
          {{- end }}
      {{- if .Values.dataProtection.enabled }}
      volumes:
        - name: dp-keys
          persistentVolumeClaim:
            claimName: {{ include "canteen.fullname" . }}-dp
      {{- end }}
